version: '3.1'

services:

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 5000
      CONNECTION_TYPE: localfile
      CONNECTION_STRING: /app/src/service/task/tasks.json
    ports:
      - "5000:5000"
